name: CI

on:
  push:
    branches: [libretro, ci_testing]

  pull_request:

jobs:
  build_mxe:
    strategy:
      matrix:
        config:
          - {triplet: i686-w64-mingw32.static, dynarec: x86, zip_name: windows-x86.zip}
          - {triplet: x86_64-w64-mingw32.static, dynarec: x86_64, zip_name: windows-x64.zip}

    runs-on: ubuntu-16.04

    env:
      CC: gcc
      platform: win
      TARGET_TRIPLET: ${{ matrix.config.triplet }}
      STATIC_LIBCXX: 0
      BUNDLED_AUDIO_CODECS: 0
      BUNDLED_LIBSNDFILE: 0
      BUNDLED_SDL: 0
      WITH_DYNAREC: ${{ matrix.config.dynarec }}

    steps:
    - uses: actions/checkout@v2
    - name: Init submodules
      run: git submodule update --depth 1 --init

    - name: Install deps
      run: sudo apt-get install
        ninja-build

    - name: Set up MXE environment
      run: wget -q 'https://github.com/realnc/stuff/releases/download/stuff/mxe.tar.xz' -O- | sudo tar xJ -C /opt

    - name: Build
      working-directory: ./libretro
      run: |
        source /opt/mxe/mxe-env.sh
        make deps
        make -j`nproc`
        ${{ matrix.config.triplet }}-strip dosbox_core_libretro.dll
        zip -9 ${{ matrix.config.zip_name }} dosbox_core_libretro.dll

    - name: Upload artifact
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.config.zip_name }}
        path: libretro/${{ matrix.config.zip_name }}

  build_linux_64:
    runs-on: ubuntu-16.04

    env:
      CC: gcc-9
      CXX: g++-9
      platform: unix
      STATIC_LIBCXX: 1
      BUNDLED_AUDIO_CODECS: 1
      BUNDLED_LIBSNDFILE: 1
      BUNDLED_SDL: 1
      WITH_DYNAREC: x86_64

    steps:
    - uses: actions/checkout@v2
    - name: Init submodules
      run: git submodule update --depth 1 --init

    - name: Install deps
      run: sudo apt-get install
        libasound2-dev
        libglib2.0-dev
        ninja-build

    - name: Build
      working-directory: ./libretro
      run: |
        make deps
        make -j`nproc`
        strip dosbox_core_libretro.so
        zip -9 linux-x64.zip dosbox_core_libretro.so

    - name: Upload artifact
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@v1
      with:
        name: linux-x64.zip
        path: libretro/linux-x64.zip

  build_macos:
    runs-on: macos-10.15

    env:
      platform: osx
      WITH_DYNAREC: x86_64
      STATIC_LIBCXX: 0
      BUNDLED_AUDIO_CODECS: 0
      BUNDLED_LIBSNDFILE: 0
      BUNDLED_SDL: 0
      PKG_CONFIG_FLAGS: --static

    steps:
    - uses: actions/checkout@v2
    - name: Init submodules
      run: git submodule update --depth 1 --init

    - name: Build glib
      run: brew reinstall --build-from-source ./libretro/deps/glib.rb

    - name: Install deps
      run: brew install
        libsndfile
        ninja
        pkg-config
        sdl_net

    # Since macOS is developed by monkeys, we have to do this shit to get static linking against
    # homebrew-installed libraries.
    - name: Symlink static homebrew libs
      working-directory: ./libretro
      run: |
        mkdir static_libs
        ln -s /usr/local/{lib,opt/gettext/lib,opt/libffi/lib}/*.a static_libs/

    - name: Build
      working-directory: ./libretro
      run: |
        make deps
        export LDFLAGS="-L $PWD/static_libs"
        make -j`sysctl -n hw.ncpu`
        strip -u -r -S dosbox_core_libretro.dylib
        zip -9 macOS-x64.zip dosbox_core_libretro.dylib

    - name: Upload artifact
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@v1
      with:
        name: macOS-x64.zip
        path: libretro/macOS-x64.zip

  upload_build:
    if: github.event_name == 'push' && github.ref == 'refs/heads/libretro'
    runs-on: ubuntu-16.04
    needs: [build_mxe, build_linux_64, build_macos]

    steps:
    - uses: actions/download-artifact@v1
      with:
        name: windows-x64.zip
    - uses: actions/download-artifact@v1
      with:
        name: windows-x86.zip
    - uses: actions/download-artifact@v1
      with:
        name: linux-x64.zip
    - uses: actions/download-artifact@v1
      with:
        name: macOS-x64.zip

    - uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest_build"
        prerelease: true
        title: "Latest Build"
        files: |
          windows-x64.zip
          windows-x86.zip
          linux-x64.zip
          macOS-x64.zip
